version: 2

project_name: nanodoc

builds:
  - id: nanodoc
    main: ./cmd/nanodoc
    binary: nanodoc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: nanodoc-archive
    ids: [nanodoc]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "nanodoc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "README.md"
      - "LICENSE"
      - src: completions/*
        dst: completions
        strip_parent: true
      - src: man/man1/*
        dst: man/man1
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - ids: [nanodoc-archive]
    name: nanodoc
    repository:
      owner: arthur-debert
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # Use debug directory if DEBUG env var is set, otherwise use Formula
    directory: '{{ if .Env.DEBUG }}debug{{ else }}Formula{{ end }}'
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/arthur-debert/nanodoc-go"
    description: "A minimalist document bundler"
    license: "MIT"
    test: |
      system "#{bin}/nanodoc --help"
    install: |
      bin.install "nanodoc"
      
      # Install shell completions
      bash_completion.install "completions/nanodoc.bash"
      zsh_completion.install "completions/nanodoc.zsh"
      fish_completion.install "completions/nanodoc.fish"
      
      # Install man page
      man1.install "man/man1/nanodoc.1.gz"

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: nanodoc
    builds: [nanodoc]
    formats: [deb, rpm, apk]
    package_name: nanodoc
    file_name_template: "nanodoc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/arthur-debert/nanodoc-go"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "A minimalist document bundler"
    license: "MIT"
    section: utils
    priority: optional

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
