version: 2

project_name: my-awesome-cli

builds:
  - id: my-awesome-cli
    main: ./cmd/my-awesome-cli
    binary: my-awesome-cli
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: my-awesome-cli-archive
    ids: [my-awesome-cli]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "my-awesome-cli-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "README.md"
      - "LICENSE"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - ids: [my-awesome-cli-archive]
    name: my-awesome-cli
    repository:
      owner: arthur-debert
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # Use debug directory if DEBUG env var is set, otherwise use Formula
    directory: '{{ if .Env.DEBUG }}debug{{ else }}Formula{{ end }}'
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/arthur-debert/my-awesome-cli"
    description: "Description of your CLI tool"
    license: "MIT"
    test: |
      system "#{bin}/my-awesome-cli --help"
    install: |
      bin.install "my-awesome-cli"

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: my-awesome-cli
    builds: [my-awesome-cli]
    formats: [deb, rpm, apk]
    package_name: my-awesome-cli
    file_name_template: "my-awesome-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/arthur-debert/my-awesome-cli"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "Description of your CLI tool"
    license: "MIT"
    section: utils
    priority: optional

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
