name: Package Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  python-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
          cache-key-prefix: "test-env-${{ matrix.python-version }}"

      - name: Publish
        id: publish
        run: source .venv/bin/activate ./bin/publish
